backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Mainpitch", name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: markdown}]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    folder: "src/pages/page"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subheading", name: subheading, widget: string}
      - {label: "Image", name: image, widget: image}
      - {label: "Mainpitch", name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: markdown}]}
      - {label: "Main", name: main, widget: object, fields: [
              {label: Content, name: content, widget: list, fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: Header, name: header, widget: string, required: false},
                {label: Text, name: text, widget: markdown}]}]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "pages-global"
    label: "Global"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: markdown}]}
          - {label: Mainbody, name: mainbody, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Intro, name: intro, widget: markdown},
              {label: Image, name: image1, widget: object,fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]},
              {label: Content, name: content, widget: markdown},
            ]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [
              {label: Blurbs, name: blurbs, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Text, name: text, widget: text}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: markdown}]}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
